counter:
  title: "&7Teleportacja nastąpi za: &f%time% sekund!"
  title_constant: "&c&lTeleportacja"
  time: 5
messages:
  reload: "&aKonfiguracja została przeładowana!"
  only_players: "&cPodana komenda jest dostępna tylko dla graczy!"
  no_permission: "&cNie masz uprawnień do używania tej komendy!"
  already_teleporting: "&cJesteś już w trakcie teleportacji!"
  spawn_not_set: "&cLokalizacja spawnu nie jest ustawiona! Ustaw ją za pomocą /setspawn."
  plugin_disabled: "&cPlugin jest wyłączony, nie można rozpocząć teleportacji."
  teleport_cancelled: "&cTeleportacja została przerwana!"
  teleport_success: "&aZostałeś przeteleportowany na spawn!"
sounds:
  teleport_countdown: BLOCK_NOTE_BLOCK_HAT
  teleport_success: ENTITY_PLAYER_LEVELUP
  teleport_cancelled: BLOCK_ANVIL_LAND